name: My first pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkput@v4
            - name: Build image
              run: docker build -t stephen2012/ciportfolio .
            - name: List images
              run: docker images
              
